#!/usr/bin/env python3
"""
재료 테이블 스키마 변경: name → name_ko, name_en 분리
"""
import sqlite3
import json
import re
import os

DB_PATH = os.path.join(os.path.dirname(__file__), '..', 'database', 'ihavenomenu.db')

# 영문 → 한글 재료명 매핑 (일반적인 재료들)
EN_TO_KO_MAPPING = {
    # 육류
    'beef': '소고기',
    'ground beef': '다진 소고기',
    'pork': '돼지고기',
    'ground pork': '다진 돼지고기',
    'chicken': '닭고기',
    'chicken breast': '닭가슴살',
    'chicken thigh': '닭다리살',
    'lamb': '양고기',
    'duck': '오리고기',
    'bacon': '베이컨',
    'ham': '햄',
    'sausage': '소시지',
    'beef stock': '소고기 육수',
    'chicken stock': '닭고기 육수',
    'mixed beef cuts': '모듬 소고기',

    # 해산물
    'fish': '생선',
    'salmon': '연어',
    'tuna': '참치',
    'shrimp': '새우',
    'squid': '오징어',
    'crab': '게',
    'clam': '조개',
    'mussel': '홍합',
    'oyster': '굴',
    'anchovy': '멸치',
    'mackerel': '고등어',
    'cod': '대구',
    'octopus': '문어',
    'scallop': '가리비',
    'lobster': '랍스터',
    'prawn': '왕새우',

    # 채소
    'garlic': '마늘',
    'onion': '양파',
    'green onion': '파',
    'scallion': '쪽파',
    'ginger': '생강',
    'carrot': '당근',
    'potato': '감자',
    'sweet potato': '고구마',
    'tomato': '토마토',
    'plum tomatoes': '방울토마토',
    'cucumber': '오이',
    'cabbage': '양배추',
    'lettuce': '상추',
    'spinach': '시금치',
    'broccoli': '브로콜리',
    'cauliflower': '콜리플라워',
    'celery': '셀러리',
    'mushroom': '버섯',
    'bell pepper': '피망',
    'red pepper': '빨간 피망',
    'green pepper': '청피망',
    'pepper': '피망',
    'chili pepper': '고추',
    'zucchini': '호박',
    'squash': '단호박',
    'eggplant': '가지',
    'corn': '옥수수',
    'peas': '완두콩',
    'bean sprouts': '숙주',
    'asparagus': '아스파라거스',
    'radish': '무',
    'korean radish': '무',
    'daikon': '무',
    'leek': '리크',
    'pumpkin': '호박',
    'kale': '케일',
    'bok choy': '청경채',
    'napa cabbage': '배추',
    'chinese cabbage': '배추',
    'black beans': '검은콩',
    'cornstarch': '전분',

    # 양념/소스
    'salt': '소금',
    'sugar': '설탕',
    'soy sauce': '간장',
    'sesame oil': '참기름',
    'vegetable oil': '식용유',
    'olive oil': '올리브유',
    'extra virgin olive oil': '엑스트라 버진 올리브유',
    'cooking oil': '식용유',
    'high heat cooking oil': '고온용 식용유',
    'vinegar': '식초',
    'rice vinegar': '쌀식초',
    'pepper': '후추',
    'black pepper': '흑후추',
    'white pepper': '백후추',
    'red pepper flakes': '고춧가루',
    'gochugaru': '고춧가루',
    'gochujang': '고추장',
    'red pepper paste': '고추장',
    'doenjang': '된장',
    'miso': '미소',
    'fish sauce': '액젓',
    'oyster sauce': '굴소스',
    'hoisin sauce': '호이신 소스',
    'teriyaki sauce': '데리야끼 소스',
    'ketchup': '케첩',
    'mayonnaise': '마요네즈',
    'mustard': '머스타드',
    'honey': '꿀',
    'maple syrup': '메이플 시럽',
    'worcestershire sauce': '우스터 소스',
    'cumin': '커민',
    'oregano': '오레가노',
    'paprika': '파프리카',
    'cinnamon': '계피',
    'curry powder': '커리 가루',
    'bay leaf': '월계수 잎',
    'thyme': '타임',
    'rosemary': '로즈마리',
    'basil': '바질',
    'parsley': '파슬리',
    'cilantro': '고수',
    'coriander': '고수',
    'mint': '민트',
    'dill': '딜',
    'chili powder': '고춧가루',
    'turmeric': '강황',
    'cardamom': '카다몬',
    'nutmeg': '육두구',
    'cloves': '정향',
    'star anise': '팔각',
    'pico de gallo sauce': '피코 데 가요 소스',

    # 유제품/계란
    'egg': '계란',
    'eggs': '계란',
    'milk': '우유',
    'cream': '크림',
    'heavy cream': '생크림',
    'sour cream': '사워크림',
    'soured cream and chive dip': '사워크림 차이브 딥',
    'butter': '버터',
    'cheese': '치즈',
    'mozzarella': '모짜렐라',
    'mozzarella cheese': '모짜렐라 치즈',
    'parmesan': '파마산',
    'cheddar': '체다',
    'cream cheese': '크림치즈',
    'yogurt': '요거트',
    'greek yogurt': '그릭 요거트',

    # 곡류/면
    'rice': '쌀',
    'flour': '밀가루',
    'bread': '빵',
    'noodles': '면',
    'pasta': '파스타',
    'spaghetti': '스파게티',
    'ramen': '라면',
    'udon': '우동',
    'soba': '소바',
    'bread crumbs': '빵가루',
    'oats': '귀리',
    'quinoa': '퀴노아',
    'barley': '보리',
    'naan bread': '난 빵',
    'corn arepa filled with mozarella cheese': '모짜렐라 치즈 아레파',

    # 콩/두부/견과류
    'tofu': '두부',
    'beans': '콩',
    'soybeans': '대두',
    'kidney beans': '강낭콩',
    'chickpeas': '병아리콩',
    'lentils': '렌틸콩',
    'peanuts': '땅콩',
    'almonds': '아몬드',
    'walnuts': '호두',
    'cashews': '캐슈넛',
    'pine nuts': '잣',
    'sesame seeds': '참깨',

    # 과일
    'apple': '사과',
    'banana': '바나나',
    'fried ripe bananas': '튀긴 바나나',
    'orange': '오렌지',
    'lemon': '레몬',
    'lime': '라임',
    'grape': '포도',
    'strawberry': '딸기',
    'blueberry': '블루베리',
    'mango': '망고',
    'pineapple': '파인애플',
    'watermelon': '수박',
    'peach': '복숭아',
    'pear': '배',
    'cherry': '체리',
    'avocado': '아보카도',

    # 기타
    'water': '물',
    'ice': '얼음',
    'seaweed': '김',
    'nori': '김',
    'kimchi': '김치',
    'toasted sesame seeds': '볶은 참깨',

    # 추가 재료들 (번역 필요했던 항목들)
    'msg': '조미료',
    'chorizo': '초리조',
    'morcilla': '모르시야',
    'lean minced steak': '다진 스테이크',
    'minced steak': '다진 스테이크',
    'cooked beetroot': '익힌 비트',
    'beetroot': '비트',
    'red beet root': '비트',
    'rocket': '루꼴라',
    'arugula': '루꼴라',
    'dry sherry': '드라이 셰리',
    'sherry': '셰리',
    'sirloin steak': '등심 스테이크',
    'sirloin': '등심',
    'rapeseed oil': '유채유',
    'canola oil': '카놀라유',
    'sunflower oil': '해바라기유',
    'red wine': '레드 와인',
    'white wine': '화이트 와인',
    'wine': '와인',
    'puff pastry': '퍼프 페이스트리',
    'shortcrust pastry': '쇼트크러스트 페이스트리',
    'pastry': '페이스트리',
    'shallots': '샬롯',
    'shallot': '샬롯',
    'challots': '샬롯',
    'stout': '스타우트',
    'beer': '맥주',
    'goose fat': '거위 기름',
    'duck fat': '오리 기름',
    'bouquet garni': '부케 가르니',
    'celeriac': '셀러리악',
    'bay leaves': '월계수 잎',
    'chilli powder': '칠리 파우더',
    'swede': '루타바가',
    'turnip': '순무',
    'baking powder': '베이킹파우더',
    'baking soda': '베이킹소다',
    'suet': '수에트',
    'lard': '라드',
    'chimichurri sauce': '치미추리 소스',
    'sesame seed oil': '참기름',
    'green chilli': '청고추',
    'green chili': '청고추',
    'birds-eye chillies': '태국 고추',
    'birds eye chillies': '태국 고추',
    'tamarind paste': '타마린드 페이스트',
    'tamarind': '타마린드',
    'creme fraiche': '크렘 프레쉬',
    'sesame seed burger buns': '참깨 번',
    'burger buns': '햄버거 번',
    'buns': '번',
    'prunes': '말린 자두',
    'juniper berries': '주니퍼 베리',
    'ancho chillies': '안초 칠리',
    'dried apricots': '말린 살구',
    'apricot': '살구',
    'vegetable stock cube': '야채 육수 큐브',
    'vegetable stock': '야채 육수',
    'stock cube': '육수 큐브',
    'molasses': '당밀',
    'yeast': '이스트',
    'instant yeast': '인스턴트 이스트',
    'dried leaves of summer savoury': '말린 세이보리',
    'savoury': '세이보리',
    'ground clove': '간 정향',
    'ground cloves': '간 정향',
    'courgettes': '애호박',
    'courgette': '애호박',
    'mct oil': 'MCT 오일',
    'shredded meat': '찢은 고기',

    # 추가 양념/허브
    'sage': '세이지',
    'tarragon': '타라곤',
    'chervil': '쉐르빌',
    'marjoram': '마조람',
    'fennel': '펜넬',
    'fennel seeds': '펜넬씨',
    'caraway seeds': '캐러웨이씨',
    'fenugreek': '호로파',
    'sumac': '수막',
    'saffron': '사프란',
    'allspice': '올스파이스',
    'five spice': '오향',
    'chinese five spice': '오향',
    'garam masala': '가람 마살라',
    'za\'atar': '자타르',
    'ras el hanout': '라스 엘 하누트',
    'harissa': '하리사',
    'sriracha': '스리라차',
    'sambal': '삼발',
    'tahini': '타히니',
    'hummus': '후무스',

    # 추가 유제품
    'feta': '페타 치즈',
    'feta cheese': '페타 치즈',
    'goat cheese': '염소 치즈',
    'ricotta': '리코타',
    'mascarpone': '마스카포네',
    'brie': '브리 치즈',
    'gruyere': '그뤼에르 치즈',
    'blue cheese': '블루 치즈',
    'halloumi': '할루미',
    'paneer': '파니르',
    'ghee': '기',
    'buttermilk': '버터밀크',
    'condensed milk': '연유',
    'evaporated milk': '무가당 연유',
    'coconut milk': '코코넛 밀크',
    'coconut cream': '코코넛 크림',
    'coconut oil': '코코넛 오일',
    'coconut': '코코넛',

    # 추가 해산물
    'haddock': '해덕',
    'halibut': '넙치',
    'sea bass': '농어',
    'trout': '송어',
    'sardines': '정어리',
    'whitebait': '흰살 생선',
    'monkfish': '아귀',
    'sea bream': '도미',
    'tilapia': '틸라피아',
    'catfish': '메기',
    'eel': '장어',
    'cuttlefish': '갑오징어',
    'razor clams': '맛조개',
    'cockles': '꼬막',
    'whelks': '소라',
    'crayfish': '가재',

    # 추가 육류
    'veal': '송아지고기',
    'venison': '사슴고기',
    'rabbit': '토끼고기',
    'goat': '염소고기',
    'offal': '내장',
    'liver': '간',
    'kidney': '콩팥',
    'tripe': '양',
    'oxtail': '꼬리',
    'tongue': '혀',
    'minced meat': '다진 고기',
    'mince': '다진 고기',
    'stewing beef': '스튜용 소고기',
    'braising steak': '찜용 스테이크',
    'ribeye': '립아이',
    'rib eye': '립아이',
    't-bone': '티본',
    'fillet': '안심',
    'tenderloin': '안심',
    'flank steak': '양지',
    'skirt steak': '치마살',
    'brisket': '양지머리',
    'chuck': '목심',
    'rump': '엉덩이살',
    'prosciutto': '프로슈토',
    'pancetta': '판체타',
    'salami': '살라미',
    'pepperoni': '페퍼로니',

    # 추가 채소
    'artichoke': '아티초크',
    'endive': '엔다이브',
    'radicchio': '라디키오',
    'chicory': '치커리',
    'watercress': '물냉이',
    'spring greens': '봄동',
    'collard greens': '콜라드 그린',
    'swiss chard': '근대',
    'sorrel': '수영',
    'samphire': '샘파이어',
    'kohlrabi': '콜라비',
    'jerusalem artichoke': '뚱딴지',
    'parsnip': '파스닙',
    'butternut squash': '버터넛 스쿼시',
    'acorn squash': '도토리 호박',
    'spaghetti squash': '스파게티 스쿼시',
    'delicata squash': '델리카타 스쿼시',
    'chayote': '차요테',
    'okra': '오크라',
    'plantain': '플랜틴',
    'cassava': '카사바',
    'yam': '참마',
    'taro': '토란',
    'lotus root': '연근',
    'burdock': '우엉',
    'bamboo shoots': '죽순',
    'water chestnuts': '마름',
    'hearts of palm': '야자 순',
    'palm hearts': '야자 순',

    # 추가 과일
    'papaya': '파파야',
    'passion fruit': '패션프루트',
    'guava': '구아바',
    'lychee': '리치',
    'dragon fruit': '용과',
    'pomegranate': '석류',
    'fig': '무화과',
    'figs': '무화과',
    'dates': '대추야자',
    'date': '대추야자',
    'raisins': '건포도',
    'sultanas': '건포도',
    'currants': '건포도',
    'cranberries': '크랜베리',
    'dried cranberries': '말린 크랜베리',
    'goji berries': '구기자',
    'acai': '아사이',
    'kiwi': '키위',
    'persimmon': '감',
    'quince': '모과',
    'plum': '자두',
    'apricots': '살구',
    'nectarine': '천도복숭아',
    'grapefruit': '자몽',
    'tangerine': '귤',
    'mandarin': '만다린',
    'clementine': '클레멘타인',
    'blood orange': '블러드 오렌지',
    'kumquat': '금귤',
    'starfruit': '스타프루트',
    'carambola': '스타프루트',
    'jackfruit': '잭프루트',
    'durian': '두리안',
    'rambutan': '람부탄',
    'mangosteen': '망고스틴',
    'longan': '용안',
    'melon': '멜론',
    'honeydew': '허니듀 멜론',
    'cantaloupe': '칸탈루프 멜론',
    'rock melon': '멜론',
    'raspberries': '라즈베리',
    'raspberry': '라즈베리',
    'blackberries': '블랙베리',
    'blackberry': '블랙베리',
    'gooseberries': '구스베리',
    'gooseberry': '구스베리',
    'elderberries': '엘더베리',
    'mulberries': '뽕나무열매',

    # 추가 곡류/면
    'couscous': '쿠스쿠스',
    'bulgur': '불구르',
    'freekeh': '프리케',
    'farro': '파로',
    'spelt': '스펠트',
    'millet': '기장',
    'buckwheat': '메밀',
    'wild rice': '야생 쌀',
    'basmati rice': '바스마티 쌀',
    'jasmine rice': '재스민 쌀',
    'arborio rice': '아르보리오 쌀',
    'risotto rice': '리조또 쌀',
    'sushi rice': '초밥 쌀',
    'sticky rice': '찹쌀',
    'glutinous rice': '찹쌀',
    'rice noodles': '쌀국수',
    'vermicelli': '버미첼리',
    'glass noodles': '당면',
    'cellophane noodles': '당면',
    'egg noodles': '계란면',
    'lasagna': '라자냐',
    'lasagne': '라자냐',
    'penne': '펜네',
    'fusilli': '푸실리',
    'rigatoni': '리가토니',
    'linguine': '링귀네',
    'fettuccine': '페투치니',
    'tagliatelle': '탈리아텔레',
    'pappardelle': '파파르델레',
    'orzo': '오르조',
    'gnocchi': '뇨키',
    'ravioli': '라비올리',
    'tortellini': '토르텔리니',
    'macaroni': '마카로니',
    'pita bread': '피타 빵',
    'flatbread': '플랫브레드',
    'tortilla': '토르티야',
    'wrap': '랩',
    'croissant': '크루아상',
    'brioche': '브리오슈',
    'ciabatta': '치아바타',
    'focaccia': '포카치아',
    'sourdough': '사워도우',
    'baguette': '바게트',

    # 추가 콩/견과류
    'cannellini beans': '카넬리니 콩',
    'butter beans': '버터 빈',
    'lima beans': '리마 콩',
    'borlotti beans': '보를로티 콩',
    'pinto beans': '핀토 콩',
    'navy beans': '네이비 빈',
    'mung beans': '녹두',
    'adzuki beans': '팥',
    'edamame': '에다마메',
    'split peas': '으깬 완두콩',
    'red lentils': '빨간 렌틸',
    'green lentils': '초록 렌틸',
    'brown lentils': '갈색 렌틸',
    'puy lentils': '퓌 렌틸',
    'hazelnuts': '헤이즐넛',
    'macadamia': '마카다미아',
    'pecans': '피칸',
    'pistachios': '피스타치오',
    'brazil nuts': '브라질 넛',
    'chestnuts': '밤',
    'roasted chestnuts': '구운 밤',
    'sunflower seeds': '해바라기씨',
    'pumpkin seeds': '호박씨',
    'chia seeds': '치아씨',
    'flax seeds': '아마씨',
    'flaxseed': '아마씨',
    'hemp seeds': '햄프씨',
    'poppy seeds': '양귀비씨',

    # 추가 번역 필요 재료들 (2차)
    'aubergine': '가지',
    'green olives': '그린 올리브',
    'olives': '올리브',
    'black olives': '블랙 올리브',
    'whole wheat': '통밀',
    'red chilli': '홍고추',
    'red chili': '홍고추',
    'doubanjiang': '두반장',
    'massaman curry paste': '마사만 커리 페이스트',
    'chopped chive': '다진 차이브',
    'chives': '차이브',
    'mulukhiyah': '몰로키아',
    'scotch bonnet': '스카치 보닛',
    'jalapeno': '할라피뇨',
    'jalapeño': '할라피뇨',
    'brandy': '브랜디',
    'cognac': '코냑',
    'rum': '럼',
    'whiskey': '위스키',
    'vodka': '보드카',
    'tabasco sauce': '타바스코 소스',
    'tabasco': '타바스코',
    'hotsauce': '핫소스',
    'hot sauce': '핫소스',
    'chilli flakes': '칠리 플레이크',
    'chili flakes': '칠리 플레이크',
    'hind shank': '뒷다리',
    'shank': '정강이',
    'cassaba': '카사바',
    'yautia': '야우티아',
    'skirty steak': '치마살',
    'enchilada sauce': '엔칠라다 소스',
    'fajita seasoning': '파히타 시즈닝',
    'sake': '사케',
    'mirin': '미림',
    'passata': '파사타',
    'ground cardomom': '간 카다몬',
    'ground cardamom': '간 카다몬',
    'vinaigrette dressing': '비네그레트 드레싱',
    'vinaigrette': '비네그레트',
    'hard taco shells': '타코 쉘',
    'taco shells': '타코 쉘',
    'green salsa': '그린 살사',
    'salsa': '살사',
    'all-purpose seasoning': '만능 시즈닝',
    'seasoning': '시즈닝',
    'peanut oil': '땅콩유',
    'panang curry paste': '파낭 커리 페이스트',
    'dried red chillies': '말린 홍고추',
    'dried red chilies': '말린 홍고추',
    'galangal': '갈랑갈',
    'galangal paste': '갈랑갈 페이스트',
    'thai red curry paste': '태국 레드 커리 페이스트',
    'thai green curry paste': '태국 그린 커리 페이스트',
    'red curry paste': '레드 커리 페이스트',
    'green curry paste': '그린 커리 페이스트',
    'curry paste': '커리 페이스트',
    'smoky aïoli': '스모키 아이올리',
    'aioli': '아이올리',
    'stir-fry vegetables': '볶음용 채소',
    'sweet chilli sauce': '스위트 칠리 소스',
    'sweet chili sauce': '스위트 칠리 소스',
    'dulce de leche': '둘세 데 레체',
    'golden syrup': '골든 시럽',
    'corn syrup': '옥수수 시럽',
    'bicarbonate of soda': '베이킹소다',
    'vanilla extract': '바닐라 추출물',
    'vanilla': '바닐라',
    'digestive biscuits': '다이제스티브 비스킷',
    'biscuits': '비스킷',
    'cookies': '쿠키',
    'almond extract': '아몬드 추출물',
    'meringue nests': '머랭',
    'meringue': '머랭',
    'turkish delight': '터키시 딜라이트',
    'pecan nuts': '피칸',

    # 추가 재료들 (3차)
    'spring onion': '대파',
    'spring onions': '대파',
    'leeks': '리크',
    'shallot': '샬롯',
    'cornflour': '옥수수 전분',
    'corn flour': '옥수수 전분',
    'self-raising flour': '자가팽창 밀가루',
    'self raising flour': '자가팽창 밀가루',
    'plain flour': '밀가루',
    'strong bread flour': '강력분',
    'bread flour': '강력분',
    'cake flour': '박력분',
    'whole wheat flour': '통밀가루',
    'wholemeal flour': '통밀가루',
    'rye flour': '호밀가루',
    'rice flour': '쌀가루',
    'chickpea flour': '병아리콩 가루',
    'gram flour': '그램 가루',
    'semolina': '세몰리나',
    'polenta': '폴렌타',
    'cornmeal': '옥수수 가루',

    # 영국식 표현
    'coriander leaves': '고수 잎',
    'fresh coriander': '신선한 고수',
    'courgette': '애호박',
    'aubergines': '가지',
    'mangetout': '완두콩',
    'rocket leaves': '루꼴라',
    'spring onion': '대파',
    'pak choi': '청경채',
    'pak choy': '청경채',
    'caster sugar': '정백당',
    'icing sugar': '슈가파우더',
    'demerara sugar': '데메라라 설탕',
    'muscovado sugar': '머스코바도 설탕',
    'brown sugar': '황설탕',
    'dark brown sugar': '흑설탕',
    'light brown sugar': '연한 황설탕',
    'granulated sugar': '백설탕',
    'powdered sugar': '슈가파우더',
    'confectioners sugar': '슈가파우더',

    # 유지류
    'groundnut oil': '땅콩유',
    'peanut butter': '땅콩버터',
    'almond butter': '아몬드 버터',
    'cashew butter': '캐슈넛 버터',
    'tahini paste': '타히니 페이스트',
    'walnut oil': '호두유',
    'truffle oil': '트러플 오일',
    'avocado oil': '아보카도유',
    'grapeseed oil': '포도씨유',
    'flaxseed oil': '아마씨유',

    # 소스류
    'barbecue sauce': '바베큐 소스',
    'bbq sauce': '바베큐 소스',
    'tomato paste': '토마토 페이스트',
    'tomato puree': '토마토 퓌레',
    'tomato sauce': '토마토 소스',
    'marinara sauce': '마리나라 소스',
    'pesto': '페스토',
    'basil pesto': '바질 페스토',
    'red pesto': '레드 페스토',
    'tapenade': '타프나드',
    'chutney': '처트니',
    'mango chutney': '망고 처트니',
    'relish': '렐리쉬',
    'pickle': '피클',
    'pickled ginger': '절인 생강',
    'capers': '케이퍼',
    'anchovy paste': '안초비 페이스트',
    'dashi': '다시',
    'bonito flakes': '가쓰오부시',
    'kombu': '다시마',
    'nori sheets': '김',
    'wakame': '미역',
    'mirin rice wine': '미림',

    # 추가 유제품
    'double cream': '생크림',
    'single cream': '싱글 크림',
    'clotted cream': '클로티드 크림',
    'whipping cream': '휘핑크림',
    'half and half': '하프 앤 하프',
    'curd': '커드',
    'cottage cheese': '코티지 치즈',
    'quark': '쿼크',
    'labneh': '라브네',
    'skyr': '스키르',
    'kefir': '케피어',
    'unsalted butter': '무염 버터',
    'salted butter': '가염 버터',
    'clarified butter': '정제 버터',

    # 추가
    'lemon juice': '레몬즙',
    'lime juice': '라임즙',
    'orange juice': '오렌지 주스',
    'apple juice': '사과 주스',
    'lemon zest': '레몬 제스트',
    'orange zest': '오렌지 제스트',
    'lime zest': '라임 제스트',
    'citrus zest': '시트러스 제스트',

    # 디저트/제과 재료 (4차)
    'pink food colouring': '핑크 식용색소',
    'food colouring': '식용색소',
    'food coloring': '식용색소',
    'yellow food colouring': '노란 식용색소',
    'marzipan': '마지팬',
    'almond paste': '아몬드 페이스트',
    'frozen mixed berries': '냉동 믹스베리',
    'mixed berries': '믹스베리',
    'blackcurrant jam': '블랙커런트 잼',
    'jam': '잼',
    'marmalade': '마멀레이드',
    'hazlenuts': '헤이즐넛',
    'cashew nuts': '캐슈넛',
    'dried fruit': '말린 과일',
    'dark chocolate chips': '다크 초콜릿 칩',
    'chocolate chips': '초콜릿 칩',
    'white chocolate chips': '화이트 초콜릿 칩',
    'unsweetened cocoa': '무가당 코코아',
    'cacao': '카카오',
    'cocoa': '코코아',
    'cocoa powder': '코코아 파우더',
    'mars bar': '마스 바',
    'dark chocolate': '다크 초콜릿',
    'white chocolate': '화이트 초콜릿',
    'milk chocolate': '밀크 초콜릿',
    'plain chocolate': '플레인 초콜릿',
    'chocolate': '초콜릿',
    'christmas pudding': '크리스마스 푸딩',
    'grand marnier': '그랑 마르니에',
    'custard': '커스타드',
    'custard powder': '커스타드 파우더',
    'dutch stroop': '네덜란드 시럽',
    'strawberries': '딸기',
    'fruit mix': '과일 믹스',
    'miniature marshmallows': '미니 마시멜로',
    'marshmallows': '마시멜로',
    'marshmallow': '마시멜로',
    'dried cherries': '말린 체리',
    'knafeh': '크나페',
    'shortening': '쇼트닝',
    'vegetable shortening': '식물성 쇼트닝',
    'blueberries': '블루베리',
    'black treacle': '블랙 트리클',
    'treacle': '트리클',
    'oatmeal': '오트밀',
    'rolled oats': '롤드 오츠',
    'unflavoured gelatin': '무향 젤라틴',
    'gelatine leafs': '젤라틴 잎',
    'gelatin': '젤라틴',
    'gelatine': '젤라틴',
    'peanut brittle': '피넛 브리틀',
    'pistachio paste': '피스타치오 페이스트',
    'sevaiiya': '세바이야',
    'malai': '말라이',
    'almond essence': '아몬드 에센스',
    'pretzels': '프레첼',
    'pretzel': '프레첼',
    'caramel': '카라멜',
    'caramel sauce': '카라멜 소스',
    'saskatoon berries': '사스카툰 베리',
    'rhubarb': '루바브',
    'food color': '식용색소',
    'agar': '한천',
    'agar agar': '한천',
    'pectin': '펙틴',
    'cream of tartar': '주석산',
    'baking spray': '베이킹 스프레이',
    'parchment paper': '유산지',
    'almond flour': '아몬드 가루',
    'coconut flour': '코코넛 가루',
    'desiccated coconut': '코코넛 가루',
    'shredded coconut': '채썬 코코넛',
    'coconut flakes': '코코넛 플레이크',
    'candied fruit': '설탕절임 과일',
    'candied ginger': '생강 설탕절임',
    'crystallized ginger': '크리스탈 진저',
    'sprinkles': '스프링클',
    'fondant': '퐁당',
    'royal icing': '로얄 아이싱',
    'frosting': '프로스팅',
    'buttercream': '버터크림',
    'ganache': '가나슈',
    'glaze': '글레이즈',
    'sponge cake': '스펀지 케이크',
    'ladyfingers': '레이디핑거',
    'puff pastry sheets': '퍼프 페이스트리 시트',
    'phyllo dough': '필로 도우',
    'filo pastry': '필로 페이스트리',
    'pie crust': '파이 크러스트',
    'graham crackers': '그레이엄 크래커',
    'oreo cookies': '오레오 쿠키',

    # 추가 육류/가공육
    'corned beef': '콘비프',
    'pastrami': '파스트라미',
    'mortadella': '모르타델라',
    'capicola': '카피콜라',
    'speck': '스펙',
    'guanciale': '관찰레',
    'lardo': '라르도',
    'nduja': '은두야',
    'sobrassada': '소브라사다',
    'jamon': '하몽',
    'serrano ham': '세라노 햄',

    # 추가 음료/액체
    'coffee': '커피',
    'espresso': '에스프레소',
    'instant coffee': '인스턴트 커피',
    'tea': '차',
    'green tea': '녹차',
    'black tea': '홍차',
    'matcha': '말차',
    'chai': '차이',

    # 추가 조미료
    'liquid smoke': '리퀴드 스모크',
    'smoke flavoring': '훈연 향료',
    'msg': '조미료',
    'chicken bouillon': '치킨 부용',
    'beef bouillon': '비프 부용',
    'bouillon': '부용',
    'stock': '육수',
    'broth': '육수',
    'consomme': '콘소메',
    'demi-glace': '데미글라스',
    'gravy': '그레이비',
    'roux': '루',
    'white sauce': '화이트 소스',
    'bechamel': '베샤멜',
    'hollandaise': '홀란다이즈',
    'bearnaise': '베아네즈',

    # 마지막 번역 필요 재료 (5차)
    'pul biber': '풀 비베르',
    'aleppo pepper': '알레포 고추',
    'fries': '감자튀김',
    'french fries': '감자튀김',
    'doner meat': '되너 케밥 고기',
    'kebab meat': '케밥 고기',
    'khus khus': '양귀비씨',
    'biryani masala': '비리야니 마살라',
    'madras paste': '마드라스 페이스트',
    'vine leaves': '포도 잎',
    'grape leaves': '포도 잎',
    'pecorino': '페코리노',
    'pecorino romano': '페코리노 로마노',
    'ground nut oil': '땅콩유',
    'gruyère': '그뤼에르 치즈',
    'gruyere cheese': '그뤼에르 치즈',
    'turkey': '칠면조',
    'turkey breast': '칠면조 가슴살',
    'barbeque sauce': '바베큐 소스',
    'fromage frais': '프로마쥬 프레',
    'pilchards': '정어리',
    'brussels sprouts': '방울양배추',
    'brussel sprouts': '방울양배추',
    'black pudding': '블랙 푸딩',
    'blood sausage': '순대',
    'kielbasa': '키엘바사',
    'polish sausage': '폴란드 소시지',
    'sauerkraut': '사우어크라우트',
    'white sauerkraut': '화이트 사우어크라우트',
    'casabe': '카사베',
    'cider': '사이다',
    'apple cider': '애플 사이다',
    'manchego': '만체고 치즈',
    'wonton skin': '만두피',
    'wonton wrapper': '만두피',
    'dumpling wrapper': '만두피',
    'polish kabanos': '폴란드 카바노스',
    'kabanos': '카바노스',
    'barramundi': '바라문디',
    'cajun': '케이준',
    'cajun seasoning': '케이준 시즈닝',
    'red snapper': '도미',
    'snapper': '도미',
    'ground annatto': '아나토 가루',
    'annatto': '아나토',
    'farfalle': '파르팔레',
    'bow tie pasta': '파르팔레',
    'hake': '대구',
    'roasted peanut': '볶은 땅콩',
    'roasted peanuts': '볶은 땅콩',
    'petit pois': '그린 피스',
    'green peas': '그린 피스',
    'ackee': '아키',
    'frozen seafood mix': '냉동 해산물 믹스',
    'seafood mix': '해산물 믹스',
    'herring': '청어',
    'baby pak koi': '미니 청경채',
    'pak koi': '청경채',
    'bok choi': '청경채',
    'natural yoghurt': '플레인 요거트',
    'plain yogurt': '플레인 요거트',
    'callaloo': '칼라루',
    'sazon': '사존',
    'yellow masarepa': '옐로우 마사레파',
    'masarepa': '마사레파',
    'raw vegetables': '생야채',
    'tempeh': '템페',
    'cooked chestnut': '익힌 밤',
    'cooked chestnuts': '익힌 밤',
    'cranberry': '크랜베리',
    'toor dal': '투르 달',
    'chana dal': '차나 달',
    'urad dal': '우라드 달',
    'moong dal': '뭉 달',
    'dal': '달',
    'falafel': '팔라펠',
    'chilli bean paste': '칠리빈 페이스트',
    'chili bean paste': '칠리빈 페이스트',

    # 추가 인도/중동 재료
    'panch phoron': '판치 포론',
    'amchur': '암추르',
    'asafoetida': '아싸페티다',
    'hing': '힝',
    'kashmiri chili': '카슈미리 칠리',
    'kashmiri chilli': '카슈미리 칠리',
    'tandoori masala': '탄두리 마살라',
    'tikka masala': '티카 마살라',
    'chaat masala': '차트 마살라',
    'sambar powder': '삼바르 파우더',
    'rasam powder': '라삼 파우더',
    'curry leaves': '커리 잎',
    'kalonji': '칼론지',
    'nigella seeds': '니겔라씨',
    'ajwain': '아즈와인',
    'carom seeds': '캐롬씨',
    'methi': '메티',
    'dried fenugreek': '말린 호로파',
    'kasuri methi': '카수리 메티',
    'jaggery': '재거리',
    'palm sugar': '팜 슈가',
    'ghee clarified butter': '기',
    'paneer cheese': '파니르 치즈',
    'za\'tar': '자타르',
    'zaatar': '자타르',
    'baharat': '바하라트',
    'dukkah': '두카',
    'berbere': '베르베레',
    'pomegranate molasses': '석류 당밀',
    'rose water': '장미수',
    'orange blossom water': '오렌지 꽃 물',

    # 마지막 재료 (6차)
    'dried chillies': '말린 고추',
    'dried chilies': '말린 고추',
    'chinese sesame sauce': '중국식 참깨 소스',
    'chinese sesame paste': '중국식 참깨 페이스트',
    'chinese leaf': '배추',
    'soya bean': '대두',
    'soya beans': '대두',
    'roasted vegetables': '구운 야채',
    'mixed grain': '잡곡',
    'multigrain': '잡곡',
    'english muffins': '잉글리쉬 머핀',
    'english muffin': '잉글리쉬 머핀',
}


def is_korean(text):
    """텍스트가 한글을 포함하는지 확인"""
    return bool(re.search('[가-힣]', text))


def normalize_name(name):
    """이름 정규화 (소문자, 공백 정리)"""
    return name.lower().strip()


def get_korean_translation(en_name):
    """영문 재료명을 한글로 번역"""
    normalized = normalize_name(en_name)

    # 정확히 매칭되는 경우
    if normalized in EN_TO_KO_MAPPING:
        return EN_TO_KO_MAPPING[normalized]

    # 부분 매칭 시도 (예: "fresh garlic" → "마늘")
    for en, ko in EN_TO_KO_MAPPING.items():
        if en in normalized or normalized in en:
            return ko

    return None


def migrate():
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()

    print("1. 새 컬럼 추가 (name_ko, name_en)...")
    try:
        cursor.execute("ALTER TABLE ingredients ADD COLUMN name_ko TEXT")
        print("   - name_ko 컬럼 추가됨")
    except sqlite3.OperationalError:
        print("   - name_ko 컬럼 이미 존재")

    try:
        cursor.execute("ALTER TABLE ingredients ADD COLUMN name_en TEXT")
        print("   - name_en 컬럼 추가됨")
    except sqlite3.OperationalError:
        print("   - name_en 컬럼 이미 존재")

    conn.commit()

    print("\n2. 기존 데이터 마이그레이션...")
    cursor.execute("SELECT id, name, aliases FROM ingredients")
    rows = cursor.fetchall()

    stats = {
        'korean_with_en': 0,
        'korean_without_en': 0,
        'english_with_ko': 0,
        'english_without_ko': 0,
        'english_auto_translated': 0,
    }

    untranslated = []

    for row in rows:
        id_, name, aliases_json = row

        # aliases 파싱
        aliases = []
        if aliases_json:
            try:
                aliases = json.loads(aliases_json)
                if not isinstance(aliases, list):
                    aliases = []
            except json.JSONDecodeError:
                aliases = []

        if is_korean(name):
            # 한글 재료
            name_ko = name
            # aliases에서 영문명 찾기
            name_en = None
            for alias in aliases:
                if alias and not is_korean(alias):
                    name_en = alias
                    break

            if name_en:
                stats['korean_with_en'] += 1
            else:
                stats['korean_without_en'] += 1

        else:
            # 영문 재료
            name_en = name
            # aliases에서 한글명 찾기
            name_ko = None
            for alias in aliases:
                if alias and is_korean(alias):
                    name_ko = alias
                    break

            # 자동 번역 시도
            if not name_ko:
                name_ko = get_korean_translation(name)
                if name_ko:
                    stats['english_auto_translated'] += 1

            if name_ko:
                stats['english_with_ko'] += 1
            else:
                stats['english_without_ko'] += 1
                untranslated.append(name)

        # 업데이트
        cursor.execute(
            "UPDATE ingredients SET name_ko = ?, name_en = ? WHERE id = ?",
            (name_ko, name_en, id_)
        )

    conn.commit()

    print(f"\n3. 마이그레이션 통계:")
    print(f"   - 한글 재료 (영문 있음): {stats['korean_with_en']}")
    print(f"   - 한글 재료 (영문 없음): {stats['korean_without_en']}")
    print(f"   - 영문 재료 (한글 있음): {stats['english_with_ko']}")
    print(f"   - 영문 재료 (자동 번역): {stats['english_auto_translated']}")
    print(f"   - 영문 재료 (번역 필요): {stats['english_without_ko']}")

    if untranslated:
        print(f"\n4. 번역 필요한 재료 ({len(untranslated)}개):")
        for name in untranslated[:50]:  # 처음 50개만 출력
            print(f"   - {name}")
        if len(untranslated) > 50:
            print(f"   ... 외 {len(untranslated) - 50}개")

    # 인덱스 추가
    print("\n5. 인덱스 추가...")
    try:
        cursor.execute("CREATE INDEX IF NOT EXISTS idx_ingredients_name_ko ON ingredients(name_ko)")
        cursor.execute("CREATE INDEX IF NOT EXISTS idx_ingredients_name_en ON ingredients(name_en)")
        print("   - 인덱스 생성 완료")
    except Exception as e:
        print(f"   - 인덱스 생성 오류: {e}")

    conn.commit()
    conn.close()

    print("\n마이그레이션 완료!")
    return untranslated


if __name__ == '__main__':
    untranslated = migrate()
